<footer class="footer">

  <!-- GitHub repository link -->
  <div class="footer-left">
    <a href="https://github.com/Kyle-Ong/project2.git" target="_blank">
      <i class="fab fa-github"></i> GitHub Repository
    </a>
  </div>

  <!-- Copyright -->
  <div class="footer-center">
    © 2026 Ethical Edge <br>
    <span>Integrity • Innovation • Excellence</span>
  </div>

  <!-- Jira project link -->
  <div class="footer-right">
    <a href="https://student-team-d84k44vi.atlassian.net" target="_blank">
      <i class="fab fa-jira"></i> Jira Dashboard
    </a>
  </div>

</footer>